apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: lan-pool
spec:
  addresses:
    - 192.168.0.240-192.168.0.250
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: lan-advertisement
spec:
  ipAddressPools:
    - lan-pool
